#!/bin/bash
find source/ -type f \( -name '*.h' -or -name '*.cpp' \) -print0 | xargs -0 clang-format -i
find test/ -type f \( -name '*.h' -or -name '*.cpp' \) -print0 | xargs -0 clang-format -i

# CLANG bug, leaves behind .TMP files
find . -type f -name '*.TMP' -print0 | xargs -0 rm -f